image: whiteshadow1/gitlab-baseimage:v1
services:
  - docker:24.0.5-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  TAG_VERSION: "v$CI_PIPELINE_IID"

stages:
    - build
    - deploy


build_and_push:
    stage: build
    script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/cricketplex-frontend:$TAG_VERSION frontend/
        - docker tag $DOCKER_USERNAME/cricketplex-frontend:$TAG_VERSION $DOCKER_USERNAME/cricketplex-frontend:latest

        - docker build -t $DOCKER_USERNAME/cricketplex-backend:$TAG_VERSION backend/
        - docker tag $DOCKER_USERNAME/cricketplex-backend:$TAG_VERSION $DOCKER_USERNAME/cricketplex-backend:latest

        - docker images
        - docker push $DOCKER_USERNAME/cricketplex-frontend:$TAG_VERSION
        - docker push $DOCKER_USERNAME/cricketplex-frontend:latest
        - docker push $DOCKER_USERNAME/cricketplex-backend:$TAG_VERSION
        - docker push $DOCKER_USERNAME/cricketplex-backend:latest


deploy_to_vm:
  stage: deploy

  needs:
    - build_and_push

  before_script:
    # Setup SSH
    - mkdir -p ~/.ssh

    # Create SSH private key file
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_deploy

    # Set permissions
    - chmod 600 ~/.ssh/id_deploy

    # Add server to known hosts
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

  script:
    - |
      ssh -i ~/.ssh/id_deploy ubuntu@$DEPLOY_SERVER << EOF

        set -e

        echo "Connected to server"

        cd ~/dev/cricketplex
        ls

      EOF