ALTER TABLE players ADD COLUMN nationality VARCHAR(100);
ALTER TABLE players ADD COLUMN wage INTEGER NOT NULL DEFAULT 500;
ALTER TABLE players ADD COLUMN rating INTEGER NOT NULL DEFAULT 20;
ALTER TABLE players ADD COLUMN confidence INTEGER NOT NULL DEFAULT 50;
