-- =============================================
-- V4: Ground management — stadium seating & match pitch setup
-- =============================================

-- Stadium seating configuration (one row per team)
CREATE TABLE stadium_seats (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id     UUID        NOT NULL UNIQUE REFERENCES teams(id) ON DELETE CASCADE,
    premium     INT         NOT NULL DEFAULT 2000,
    standard    INT         NOT NULL DEFAULT 8000,
    economy     INT         NOT NULL DEFAULT 12000,
    standing    INT         NOT NULL DEFAULT 3000,
    created_at  TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP   NOT NULL DEFAULT now()
);

CREATE INDEX idx_stadium_seats_team ON stadium_seats (team_id);

-- Upcoming home matches (mock schedule — will be generated by game engine later)
CREATE TABLE home_matches (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id         UUID            NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    opponent_name   VARCHAR(255)    NOT NULL,
    match_date      DATE            NOT NULL,
    competition     VARCHAR(100)    NOT NULL,
    format          VARCHAR(20)     NOT NULL DEFAULT 'T20',
    pitch_type      VARCHAR(30)     NOT NULL DEFAULT 'STANDARD',
    created_at      TIMESTAMP       NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT now()
);

CREATE INDEX idx_home_matches_team ON home_matches (team_id);
CREATE INDEX idx_home_matches_date ON home_matches (match_date);
